### PR TITLE
[fix] Circular json error for LoggingInterceptor with useGlobalInterceptors

### PR DESCRIPTION
**Pull request by juliendu11**
Sometimes there is a problem with using useGlobalInterceptors when the object has a complex structure

I had a circular json error for graphql subscriptions using redis

I just add a function to "break" the circularity and show the values

### CODE REVIEW

**Review by owen1002 — COMMENTED** [review]
Please check a possible generic solution which prevent logging extra information for circular referenced object using replacer:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

Possible solution:
```
const getCircularReplacer = () => {
  const seen = new WeakSet();
  return (key, value) => {
    if (typeof value === "object" && value !== null) {
      if (seen.has(value)) {
        return;
      }
      seen.add(value);
    }
    return value;
  };
};

JSON.stringify(circularReference, getCircularReplacer());
```

**Comment by klebeer** [comment]
What about using instead fast-safe-stringify?, it takes cares of circular stuff

https://github.com/davidmarkclements/fast-safe-stringify#readme

**Comment by juliendu11** [comment]
> Please check a possible generic solution which prevent logging extra information for circular referenced object using replacer:
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value
> 
> Possible solution:
> 
> ```
> const getCircularReplacer = () => {
>   const seen = new WeakSet();
>   return (key, value) => {
>     if (typeof value === "object" && value !== null) {
>       if (seen.has(value)) {
>         return;
>       }
>       seen.add(value);
>     }
>     return value;
>   };
> };
> 
> JSON.stringify(circularReference, getCircularReplacer());
> ```

Yes surely a better solution to do it like that

On the other hand I encounter the problem of circular JSON when connecting by WebSocket

The only place I have found to sort this out is here because it is not related to my code but to the ws connection:

````
 return next.handle().pipe(
      tap({
        next: (value) => {
          this.logger.log(`${JSON.stringify({ Response: value })}`); <= Here
        },
      }),
    );
``

**Comment by juliendu11** [comment]
> What about using instead fast-safe-stringify?, it takes cares of circular stuff
> 
> https://github.com/davidmarkclements/fast-safe-stringify#readme

Great this package I did not know, it solves my problem

**Pull request closed without merging**
